/**
 * Check out https://googlechrome.github.io/sw-toolbox/docs/master/index.html for
 * more info on how to use sw-toolbox to custom configure your service worker.
 */


'use strict';
importScripts('sw-toolbox.js');

self.toolbox.options.cache = {
  name: 'ionic-cache'
};

// pre-cache our key assets
self.toolbox.precache(
  [
    'src/img/mediumCards/card00.png',
    'src/img/mediumCards/card01.png',
    'src/img/mediumCards/card02.png',
    'src/img/mediumCards/card03.png',
    'src/img/mediumCards/card04.png',
    'src/img/mediumCards/card05.png',
    'src/img/mediumCards/card06.png',
    'src/img/mediumCards/card07.png',
    'src/img/mediumCards/card08.png',
    'src/img/mediumCards/card09.png',
    'src/img/mediumCards/card010.png',
    'src/img/mediumCards/card011.png',
    'src/img/mediumCards/card012.png',
    'src/img/mediumCards/card10.png',
    'src/img/mediumCards/card11.png',
    'src/img/mediumCards/card12.png',
    'src/img/mediumCards/card13.png',
    'src/img/mediumCards/card14.png',
    'src/img/mediumCards/card15.png',
    'src/img/mediumCards/card16.png',
    'src/img/mediumCards/card17.png',
    'src/img/mediumCards/card18.png',
    'src/img/mediumCards/card19.png',
    'src/img/mediumCards/card110.png',
    'src/img/mediumCards/card111.png',
    'src/img/mediumCards/card112.png',
    'src/img/mediumCards/card20.png',
    'src/img/mediumCards/card21.png',
    'src/img/mediumCards/card22.png',
    'src/img/mediumCards/card23.png',
    'src/img/mediumCards/card24.png',
    'src/img/mediumCards/card25.png',
    'src/img/mediumCards/card26.png',
    'src/img/mediumCards/card27.png',
    'src/img/mediumCards/card28.png',
    'src/img/mediumCards/card29.png',
    'src/img/mediumCards/card210.png',
    'src/img/mediumCards/card211.png',
    'src/img/mediumCards/card212.png',
    'src/img/mediumCards/card30.png',
    'src/img/mediumCards/card31.png',
    'src/img/mediumCards/card32.png',
    'src/img/mediumCards/card33.png',
    'src/img/mediumCards/card34.png',
    'src/img/mediumCards/card35.png',
    'src/img/mediumCards/card36.png',
    'src/img/mediumCards/card37.png',
    'src/img/mediumCards/card38.png',
    'src/img/mediumCards/card39.png',
    'src/img/mediumCards/card310.png',
    'src/img/mediumCards/card311.png',
    'src/img/mediumCards/card312.png',
    'src/img/smallCards/card00.png',
    'src/img/smallCards/card01.png',
    'src/img/smallCards/card02.png',
    'src/img/smallCards/card03.png',
    'src/img/smallCards/card04.png',
    'src/img/smallCards/card05.png',
    'src/img/smallCards/card06.png',
    'src/img/smallCards/card07.png',
    'src/img/smallCards/card08.png',
    'src/img/smallCards/card09.png',
    'src/img/smallCards/card010.png',
    'src/img/smallCards/card011.png',
    'src/img/smallCards/card012.png',
    'src/img/smallCards/card10.png',
    'src/img/smallCards/card11.png',
    'src/img/smallCards/card12.png',
    'src/img/smallCards/card13.png',
    'src/img/smallCards/card14.png',
    'src/img/smallCards/card15.png',
    'src/img/smallCards/card16.png',
    'src/img/smallCards/card17.png',
    'src/img/smallCards/card18.png',
    'src/img/smallCards/card19.png',
    'src/img/smallCards/card110.png',
    'src/img/smallCards/card111.png',
    'src/img/smallCards/card112.png',
    'src/img/smallCards/card20.png',
    'src/img/smallCards/card21.png',
    'src/img/smallCards/card22.png',
    'src/img/smallCards/card23.png',
    'src/img/smallCards/card24.png',
    'src/img/smallCards/card25.png',
    'src/img/smallCards/card26.png',
    'src/img/smallCards/card27.png',
    'src/img/smallCards/card28.png',
    'src/img/smallCards/card29.png',
    'src/img/smallCards/card210.png',
    'src/img/smallCards/card211.png',
    'src/img/smallCards/card212.png',
    'src/img/smallCards/card30.png',
    'src/img/smallCards/card31.png',
    'src/img/smallCards/card32.png',
    'src/img/smallCards/card33.png',
    'src/img/smallCards/card34.png',
    'src/img/smallCards/card35.png',
    'src/img/smallCards/card36.png',
    'src/img/smallCards/card37.png',
    'src/img/smallCards/card38.png',
    'src/img/smallCards/card39.png',
    'src/img/smallCards/card310.png',
    'src/img/smallCards/card311.png',
    'src/img/smallCards/card312.png',
    'index.html',
    'manifest.json',
    'src/style/game.css'
  ]
);

// dynamically cache any other local assets
self.toolbox.router.any('/*', self.toolbox.cacheFirst);

// for any other requests go to the network, cache,
// and then only use that cached resource if your user goes offline
self.toolbox.router.default = self.toolbox.networkFirst;